import React from 'react'
import {
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  Bot,
  BrainCircuit,
  CircleHelp,
  Check,
  CircleAlert,
  CirclePlus,
  Compass,
  Cloud,
  CloudMoon,
  Copy,
  Cpu,
  Droplets,
  Download,
  Edit3,
  Eye,
  EyeOff,
  FileDown,
  FileUp,
  Gauge,
  Gem,
  GitMerge,
  Languages,
  LoaderCircle,
  LucideIcon,
  Moon,
  Monitor,
  Flame,
  Network,
  Plus,
  Route,
  Search,
  SearchX,
  Send,
  Settings,
  SlidersHorizontal,
  Sparkles,
  SquarePlus,
  Trash2,
  Languages as Translate,
  TriangleAlert,
  Rocket,
  Wind,
  Upload,
  Users,
  Volume2,
  WandSparkles,
  Zap,
  ChevronDown,
  ChevronUp,
  ChevronRight,
  X,
} from 'lucide-react'
import { cn } from '@/lib/utils'

const ICONS = {
  translate: Translate,
  token: Gem,
  neurology: BrainCircuit,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  settings: Settings,
  tune: SlidersHorizontal,
  language: Languages,
  arrow_forward: ArrowRight,
  add: Plus,
  send: Send,
  content_copy: Copy,
  volume_up: Volume2,
  visibility: Eye,
  visibility_off: EyeOff,
  error: CircleAlert,
  warning: TriangleAlert,
  merge: GitMerge,
  swap_horiz: ArrowLeftRight,
  arrow_back: ArrowLeft,
  search: Search,
  search_off: SearchX,
  add_circle: CirclePlus,
  chevron_right: ChevronRight,
  download: Download,
  upload: Upload,
  edit: Edit3,
  delete: Trash2,
  progress_activity: LoaderCircle,
  check: Check,
  settings_suggest: WandSparkles,
  smart_toy: Bot,
  psychology: BrainCircuit,
  explore: Compass,
  air: Wind,
  rocket_launch: Rocket,
  hub: Network,
  bolt: Zap,
  groups: Users,
  local_fire_department: Flame,
  memory: Cpu,
  speed: Gauge,
  computer: Monitor,
  route: Route,
  cloud: Cloud,
  nightlight: Moon,
  cloud_circle: CloudMoon,
  auto_awesome: Sparkles,
  water_drop: Droplets,
  close: X,
  help: CircleHelp,
  question_mark: CircleHelp,
  square_plus: SquarePlus,
  add_circle_outline: CirclePlus,
  download_for_offline: FileDown,
  upload_file: FileUp,
  model: Gem,
  translate_alt: Translate,
  add_shopping_cart: Plus,
  compass: Compass,
  cloud_moon: CloudMoon,
  flame: Flame,
  droplets: Droplets,
  rocket: Rocket,
  wind: Wind,
} as const satisfies Record<string, LucideIcon>

type IconName = keyof typeof ICONS

interface IconProps extends React.SVGProps<SVGSVGElement> {
  name: IconName | string
  size?: number
}

export function Icon({ name, size = 20, className, ...props }: IconProps) {
  const Component = ICONS[name as IconName] ?? Settings
  return <Component className={cn('shrink-0', className)} size={size} {...props} />
}
